spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  jpa:
    database: H2
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

application:
  file:
    # path: /Users/simpolor/upload
    path: /Users/parksy/temp